<?php

if ( !defined( 'ABSPATH' ) )
	exit( 'No direct script access allowed' ); // Exit if accessed directly

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b3e09e3cd553',
		'title' => 'Informacje o wydarzeniu',
		'fields' => array(
			array(
				'key' => 'field_5b3e0fc4dd5cd',
				'label' => 'Data początku wydarzenia',
				'name' => 'start_date',
				'type' => 'date_picker',
				'instructions' => 'Wybierz dzień, w którym zaczyna się wydarzenie',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5b3e0fdedd5ce',
				'label' => 'Data końca wydarzenia',
				'name' => 'end_date',
				'type' => 'date_picker',
				'instructions' => 'Wybierz dzień, w którym kończy się wydarzenie',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b3f57aa6eeba',
		'title' => 'Kolejne kroki (lata)',
		'fields' => array(
			array(
				'key' => 'field_5b3f57c6f29a8',
				'label' => 'Sekcja obrazek + opis',
				'name' => 'section',
				'type' => 'repeater',
				'instructions' => 'Dodaj kolejną sekcję z opisem obrazek + tekst.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Dodaj sekcję',
				'sub_fields' => array(
					array(
						'key' => 'field_5b3f5804f29a9',
						'label' => 'Zdjęcie',
						'name' => 'img',
						'type' => 'image',
						'instructions' => 'Dodaj zdjęcie, które wyświetli się z lewej strony tekstu.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5b3f5828f29aa',
						'label' => 'Tytuł',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Wpisz tytuł, który pojawi się nad zakładkami.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b3f5855f29ab',
						'label' => 'Zakładki z opisami',
						'name' => 'accordion',
						'type' => 'repeater',
						'instructions' => 'Dodaj rozwijane zakładki z opisem.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'row',
						'button_label' => 'Dodaj zakładkę',
						'sub_fields' => array(
							array(
								'key' => 'field_5b3f58a2f5387',
								'label' => 'Tytuł zakładki',
								'name' => 'title',
								'type' => 'text',
								'instructions' => 'Wpisz tytuł rozwijanej zakładki.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b3f58b1f5388',
								'label' => 'Rozwijana treść',
								'name' => 'panel',
								'type' => 'wysiwyg',
								'instructions' => 'Wpisz tutaj treść, która rozwinie się po kliknięciu w tytuł.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-steps.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b3e0d67158c6',
		'title' => 'Ustawienia archiwum wpisów',
		'fields' => array(
			array(
				'key' => 'field_5b3e0d75d2829',
				'label' => 'Komunikat w przypadku braku nadchodzących wydarzeń.',
				'name' => 'message',
				'type' => 'wysiwyg',
				'instructions' => 'Wpisz tutaj komunikat, który pojawi się w przypadku braku nadchodzących wydarzeń.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5b3e0db7d282a',
				'label' => 'Kiedy wydarzenie trafia do archiwum?',
				'name' => 'archive_period',
				'type' => 'number',
				'instructions' => 'Wybierz po ilu miesiącach od ukończenia danego wydarzenia ma ono trafić do archiwum.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 12,
				'step' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-blog.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;

?>